const BASE_URL = 'http://192.168.1.6:8080/api/';
const USER_JWT_TIME_EXPIRATON = 604800000;
const USER_JWT_COOKIE_NAME = 'USER_JWT';
const USER_LOCAL_STORAGE_NAME = 'USER_LOGGED';
const PROJECT_TYPES = ['ML', 'NLP', 'SEARCH', 'VISION', 'ONTOLOGIES'];
const DEFAULT_VERSION_NAME = 'Lastest Version';

export {
  BASE_URL,
  USER_JWT_TIME_EXPIRATON,
  USER_JWT_COOKIE_NAME,
  USER_LOCAL_STORAGE_NAME,
  PROJECT_TYPES,
  DEFAULT_VERSION_NAME,
};
