const BASE_URL = 'http://192.168.0.18:8080/api/';
const USER_JWT_TIME_EXPIRATON = 604800000;
const USER_JWT_COOKIE_NAME = 'USER_JWT';
const USER_COOKIE_NAME = 'USER_LOGGED';
const PROJECT_TYPES = ['ML', 'NLP', 'SEARCH', 'CV', 'ONT'];

export {
  BASE_URL,
  USER_JWT_TIME_EXPIRATON,
  USER_JWT_COOKIE_NAME,
  USER_COOKIE_NAME,
  PROJECT_TYPES,
};
